apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER

          env:
            - name: SHADOW_DB_URL
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: SHADOW_DB_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: SMTP_PASS
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: SMTP_PORT
            - name: EMAIL1
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: EMAIL1
            - name: EMAIL2
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: EMAIL2
            - name: SALT_HASH
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: SALT_HASH
            - name: SECRET_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: SECRET_ACCESS_TOKEN
            - name: SECRET_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: SECRET_REFRESH_TOKEN
            - name: TIME_EXPIRING_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: TIME_EXPIRING_ACCESS_TOKEN
            - name: TIME_EXPIRING_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: TIME_EXPIRING_REFRESH_TOKEN
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: GH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: GH_CLIENT_ID
            - name: GH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: inctagram-back-config-secret
                  key: GH_CLIENT_SECRET