apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: SHADOW_DB_URL
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: SHADOW_DB_URL
             - name: SMTP_USER
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: SMTP_USER
             - name: SMTP_PASS
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: SMTP_PASS
             - name: SMTP_HOST
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: SMTP_HOST
             - name: SMTP_PORT
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: SMTP_PORT
             - name: SALT_HASH
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: SALT_HASH
             - name: SECRET_ACCESS_TOKEN
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: SECRET_ACCESS_TOKEN
             - name: SECRET_REFRESH_TOKEN
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: SECRET_REFRESH_TOKEN
             - name: TIME_EXPIRING_ACCESS_TOKEN
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: TIME_EXPIRING_ACCESS_TOKEN
             - name: TIME_EXPIRING_REFRESH_TOKEN
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: TIME_EXPIRING_REFRESH_TOKEN
             - name: GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: GOOGLE_CLIENT_ID
             - name: GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: GOOGLE_CLIENT_SECRET
             - name: GH_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: GH_CLIENT_ID
             - name: GH_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: GH_CLIENT_SECRET
             - name: APP_DOMAIN_NAME
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: APP_DOMAIN_NAME
             - name: AWS_ACCESS_KEY_ID
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: AWS_ACCESS_KEY_ID
             - name: AWS_SECRET_ACCESS_KEY
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: AWS_SECRET_ACCESS_KEY
             - name: AWS_S3_REGION
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: AWS_S3_REGION
             - name: BUCKET
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: BUCKET
             - name: FILE_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: FILE_SERVICE_HOST
             - name: FILE_SERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: FILE_SERVICE_PORT
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: pirates-inctagram-back-files-ms-config-secret
                   key: DATABASE_URL
